### ISSUE TITLE
buffer not persisted in hello_libpmemobj

### ISSUE THREAD

**Issue by ryanphuang** [pmem/pmdk-examples#11]
In the hello_libpmemobj example, when it persists the buffer with `pmemobj_memcpy_persist`, the size argument is using `rootp->len`. 

https://github.com/pmem/pmdk-examples/blob/550586d2cc6c088b2722a6fad0182ef89b9f832a/hello_world/libpmemobj/hello_libpmemobj.c#L81

But `rootp->len` is initially 0, so the buffer content won't be persisted or read back:

```
$ ./hello_libpmemobj -w /mnt/mem/hello.pool

Write the () string to persistent-memory.

$ ./hello_libpmemobj -r /mnt/mem/hello.pool

Read the () string from persistent-memory.
```

The issue seems to be caused by the bug fix 550586d. The size argument should be `strlen(buf)` instead or the `rootp->len` assignment should be moved before the memcpy. 

https://github.com/pmem/pmdk-examples/blob/550586d2cc6c088b2722a6fad0182ef89b9f832a/hello_world/libpmemobj/hello_libpmemobj.c#L84

I tested this change would correctly persist the buffer.

```
$ ./hello_libpmemobj -w /mnt/mem/hello.pool

Write the (Hello Persistent Memory!!!) string to persistent-memory.

$ ./hello_libpmemobj -r /mnt/mem/hello.pool

Read the (Hello Persistent Memory!!!) string from persistent-memory.
```

**Comment by eberroca** [comment]
You are correct, thanks for pointing this out !

**Comment by eberroca** [comment]
Fixed
