### ISSUE TITLE
Cannot compile - include paths in the makefile wrong?

### ISSUE THREAD

**Issue by kcleung** [pmem/pmdk-examples#9]
I am running Ubuntu 18.04 LTS on a computer with optane memory installed.  However, when I tried to compile, it fails with the following error:

./hello_libpmemobj++.hpp:36:10: fatal error: libpmemobj++/make_persistent.hpp: No such file or directory
 #include <libpmemobj++/make_persistent.hpp>

**Comment by eberroca** [comment]
Problem should be fixed now.

**Comment by hsezhiyan** [comment]
@eberroca do you mind explaining what the fix was? I'm running into the same issue.
